skip_clone: true

steps:
- name: clone
  image: woodpeckerci/plugin-git
  depends_on: []
  settings:
    lfs: false
- name: restore-cache
  image: meltwater/drone-cache
  environment: &cache_env
    AWS_ACCESS_KEY_ID:
      from_secret: s3id
    AWS_SECRET_ACCESS_KEY:
      from_secret: s3key
  depends_on: []
  pull: true
  settings: &cache_settings
    restore: true
    path_style: true
    bucket:
      from_secret: s3bucket
    region:
      from_secret: s3region
    endpoint:
      from_secret: s3url
    archive_format: 'zstd'
    compression_level: 5
    mount:
      - '.gradle'
      - '.gradle-user'
      - 'buildSrc/build'
- name: build
  image: gradle:8.12.1-jdk21
  environment:
    TERM: dumb
    GRADLE_USER_HOME: ./.gradle-user
    SIGNIFY_KEY:
      from_secret: signify_key
    SIGNIFY_PASSWORD:
      from_secret: signify_password
    ORG_GRADLE_PROJECT_SleepingTownUsername:
      from_secret: maven_username
    ORG_GRADLE_PROJECT_SleepingTownPassword:
      from_secret: maven_password
  depends_on: [clone, restore-cache]
  commands:
  - gradle clean build publish -Punsup.ci
  - gradle --stop
- name: release
  image: linuxserver/yq:3.4.3
  environment:
    FORGEJO_KEY:
      from_secret: forgejo_key
  depends_on: [build]
  commands:
  - ./update-snapshot-release.sh
- name: update-cache
  image: meltwater/drone-cache
  environment: *cache_env
  depends_on: [build]
  pull: true
  settings:
    <<: *cache_settings
    restore: false
    rebuild: true

when:
  - branch: "trunk"
    event: push
  - event: manual
