/*
 * This file is part of unsup.
 * Copyright © 2020-2025 Una Kearney
 * https://git.sleeping.town/unascribed/unsup
 *
 * unsup is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * unsup is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with unsup; if not, see <https://www.gnu.org/licenses/>.
 */

buildscript {
	repositories {
		mavenCentral()
		maven { url 'https://repo.sleeping.town' }
	}
	dependencies {
		// just used for shrinking. i've used proguard a lot and trust it
		classpath 'com.guardsquare:proguard-gradle:7.6.1'
		// for patching
		classpath 'com.unascribed:nilloader:1.3.4'
	}
}

plugins {
	id 'com.github.ben-manes.versions' version '0.52.0'
	id 'org.cadixdev.licenser' version '0.6.1'
	id 'java-library'
	id 'maven-publish'
}

import com.unascribed.sup.PlatDetect;
import com.unascribed.sup.PlatDetect.OSType;
import com.unascribed.sup.PlatDetect.ArchType;
import com.unascribed.sup.build.JarAmender;
import com.unascribed.sup.build.transformer.JarTransformer;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

def commit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=10', 'HEAD'
}.standardOutput.asText.get().trim()
def clean = providers.exec {
	commandLine 'git', 'diff-index', 'HEAD'
	ignoreExitValue = true
}.standardOutput.asText.get().trim().isEmpty()

def snapshotName = commit+(clean ? '' : '-dirty')

ext {
	platforms = OSType.values().collect { os ->
		os.supportedArchitectures.collect { arch ->
			os.lwjglName+arch.lwjglSuffix
		}
	}.flatten()
}

base {
	group = 'com.unascribed'
	archivesName = 'unsup'
	version = project.hasProperty('unsup.release') ? project.getProperty('unsup.release') : '1.1-SNAPSHOT'
}

license {
	header = project.file('HEADER')
	ignoreFailures = true
	tasks {
		auxillary {
			files.from('build.gradle')
			files.from('.woodpecker.yml')
			files.from('src/debug')
			files.from('unsup.svg')
			files.from('unsup-lowres.svg')
			files.from('update-snapshot-release.sh')
			files.from('gradle/verification-metadata.xml')
		}
		buildSrc {
			files.from('buildSrc/src')
		}
	}
	style {
		ini = 'HASH'
		svg = 'XML'
	}
}

task computeFileDates {
	def root = file('.')
	doFirst {
		copy {
			from '.'
			
			include 'src/**/*.java'
			include 'src/**/*.ini'
			include 'src/**/*.xml'
			include 'buildSrc/src/**/*.java'
			include 'build.gradle'
			include '.woodpecker.yml'
			include 'unsup.svg'
			include 'unsup-lowres.svg'
			include 'update-snapshot-release.sh'
			include 'gradle/verification-metadata.xml'
			
			includeEmptyDirs false
			
			def uncreditedAuthors = [
				// due to Weblate squash commits addon, which i have since uninstalled
				// this can get removed once all the translations get updated
				'src/main/resources/com/unascribed/sup/presets/lang/nb-NO.ini': ['Artemis'],
				'src/main/resources/com/unascribed/sup/presets/lang/ko.ini': ['Skye'],
				'src/main/resources/com/unascribed/sup/presets/lang/tok.ini': ['Jo Null'],
			]
			
			eachFile {
				try {
					def years = ['sh', '-c', "git log --format=%cd --date=iso-strict --follow '${it.path}' |cut -d- -f1 |sort -nu"].execute().text.trim().split("\n").collect { Integer.parseInt(it) }
					def authors = ['sh', '-c', "git log --format=%aN --follow '${it.path}' |grep -v '^\$' |grep -v 'Sleeping Town Weblate' |sort -u"].execute().text.trim().split("\n").toList()
					authors.addAll(uncreditedAuthors[it.path] ?: [])
					if (authors.remove('Una Kearney')) {
						// main copyright holder name first
						authors.add(0, 'Una Kearney')
					}
					
					def ranges = []
					int prev = 0
					int start = 0
					int end = 0
					def compute = {
						if (start != 0 && end != 0) {
							if (start != end) {
								ranges.add(start+'-'+end)
							} else {
								ranges.add(''+start)
							}
						}
					}
					for (int i : years) {
						if (i == prev+1) {
							end = i
						} else {
							compute()
							start = i
							end = i
						}
						prev = i
					}
					compute()
					
					file(it.path).text = file(it.path).text
						.replace('$'+'{year}', ranges.join(', '))
						.replace('$'+'{authors}', authors.join(', '))
				} catch (e) {
					e.printStackTrace()
				}
				it.exclude()
			}
			
			into 'build/tmp/trash'
		}
	}
}

afterEvaluate {
	updateLicenses.finalizedBy computeFileDates
	tasks.withType(org.cadixdev.gradle.licenser.tasks.LicenseCheck).each {
		it.enabled = false
	}
}


sourceCompatibility = targetCompatibility = 8

compileJava {
	options.release = 8
}

repositories { 
	mavenCentral()
	maven { url 'https://repo.sleeping.town' }
	exclusiveContent {
		forRepository {
			flatDir { dirs '.gradle/transformed' }
		}
		filter {
			includeGroup 'transformed'
		}
	}
}

sourceSets {
	// prevent crossing puppet/agent boundary
	puppet {
		compileClasspath += sourceSets.main.compileClasspath
		compileClasspath += sourceSets.main.output
	}
	agent {
		compileClasspath += sourceSets.main.compileClasspath
		compileClasspath += sourceSets.main.output
	}
}

configurations {
	shade
	implementation.extendsFrom shade
	transform
	transformSrc
	ogldep
	compileOnly.extendsFrom ogldep
	oglnative
}

dependencies {
	def shadeCis = {
		shade(it) {
			transitive = false
		}
	}
	def trans = {
		def dep = transform(it) { transitive = false }
		transformSrc(it+':sources') { transitive = false }
		shade "transformed:${dep.name}:${dep.version}"
	}

	trans 'com.grack:nanojson:1.9'
	shade 'net.i2p.crypto:eddsa:0.3.0'
	
	trans 'com.squareup.okhttp3:okhttp:4.12.0'
	
	shadeCis 'com.squareup.okhttp3:okhttp-brotli:4.12.0'
	shadeCis 'com.squareup.okhttp3:okhttp-dnsoverhttps:4.12.0'
	shadeCis 'com.squareup.okhttp3:okhttp-tls:4.12.0'
	
	shadeCis 'org.jetbrains.kotlin:kotlin-stdlib:1.9.10'
	shadeCis 'com.squareup.okio:okio:3.6.0'
	shadeCis 'com.squareup.okio:okio-jvm:3.6.0'
	
	trans 'com.moandjiezana.toml:toml4j:0.7.2'
	shadeCis 'org.brotli:dec:0.1.2'
	shade 'com.unascribed:flexver-java:1.1.1'
	shade 'me.saharnooby:qoi-java:1.2.1'
	
	def lwjglv = '3.3.6'
	lwjgl(it, lwjglv, 'glfw', 'opengl', 'freetype')
	ogldep "org.lwjgl:lwjgl-harfbuzz:${lwjglv}"
}

configurations.transform.resolve().each { f ->
	def outdir = project.file('.gradle/transformed')
	outdir.mkdirs()
	def out = new File(outdir, f.name)
	Files.copy(f.toPath(), out.toPath(), StandardCopyOption.REPLACE_EXISTING)
	JarTransformer.transform(out)
}

copy {
	configurations.transformSrc.resolve().each { f ->
		from f
	}
	into '.gradle/transformed'
}

jar {
	archiveClassifier = 'unfinished'
	destinationDirectory.set(file('build/tmp'))
	
	project.configurations.shade.resolve().each { f ->
		from(zipTree(f))
	}
	
	from sourceSets.puppet.output
	from sourceSets.agent.output
	
	exclude 'javax/annotation/**'
	
	duplicatesStrategy = 'fail'
	
	def mapfile = file('build/tmp/proguard.map')
	doFirst {
		def pfx = 'com/unascribed/sup/lib/'
		def relocations = [
			'com/grack/nanojson/': pfx+'nanojson/',
			'com/moandjiezana/toml/': pfx+'toml/',
			'com/unascribed/flexver/': pfx+'flexver/',
			'me/saharnooby/qoi/': pfx+'qoi/',
			'net/i2p/crypto/eddsa/': pfx+'eddsa/',
			'kotlin/': pfx+'kotlin/',
			'okhttp3/': pfx+'okhttp3/',
			'okio/': pfx+'okio/',
			'org/brotli/dec/': pfx+'brotli/',
		]
		
		mapfile.text = ""
		
		eachFile {
			def n = it.path
			def pg = false
			if (n.endsWith(".class")) {
				n = n.substring(0, n.length()-6)
				pg = true
			}
			def newName = n
			for (def en : relocations.entrySet()) {
				if (n.startsWith(en.key)) {
					newName = n.replace(en.key, en.value)
					break
				}
			}
			if (pg) {
				mapfile.append("${n} -> ${newName}:\n")
			} else {
				it.path = newName
			}
		}
	}
}

tasks.named("dependencyUpdates").configure {
	gradleReleaseChannel = 'current'
	revision = 'release'
	rejectVersionIf {
		it.candidate.version.contains("alpha") || it.candidate.version.contains("beta")
	}
}

def pgLibJars = files(
	System.properties["java.home"]+"/jmods/java.base.jmod", // everyone needs java base
	System.properties["java.home"]+"/jmods/java.desktop.jmod", // used by the puppet
	System.properties["java.home"]+"/jmods/java.management.jmod", // for the agent
	System.properties["java.home"]+"/jmods/java.xml.jmod", // html renderer in the opengl puppet
	System.properties["java.home"]+"/jmods/java.logging.jmod", // used by okhttp
)

task proguard(type: proguard.gradle.ProGuardTask) {
	dependsOn jar
	injars jar.archivePath
	libraryjars pgLibJars
	outjars 'build/tmp/proguard.jar'
	
	dontoptimize
	
	applymapping 'build/tmp/proguard.map'
	
	keep 'class com.unascribed.sup.agent.Agent { *; }'
	keep 'class com.unascribed.sup.puppet.Puppet { *; }'
	keep 'class com.unascribed.sup.Unsup { *; }'
	
	keepclassmembers 'enum * { public static **[] values(); public static ** valueOf(java.lang.String); }'
	keepclassmembernames 'class * { *; }'

	dontwarn 'com.unascribed.sup.lib.**'
	dontwarn 'org.jetbrains.annotations.**'
	dontwarn 'org.lwjgl.**'
	dontwarn 'javax.annotation.**'
	dontwarn 'com.unascribed.sup.puppet.opengl.util.GL'
	dontwarn 'sun.misc.**'
	dontwarn 'okhttp3.internal.platform.**'
	dontwarn 'lombok.**'
	dontwarn 'org.codehaus.mojo.animal_sniffer.**'
	
	keepattributes '*'
	
	verbose
}

task extractPublicSuffix(type: Copy) {
	inputs.files configurations.shade.resolve()
	outputs.dir 'build/tmp/publicsuffix'
	configurations.shade.resolve().each { f ->
		from zipTree(f)
	}
	
	include '**/publicsuffixes.gz'
	includeEmptyDirs false
	
	into 'build/tmp/publicsuffix'
}

task popPublicSuffix(type: Exec) {
	def in = 'build/tmp/publicsuffix/okhttp3/internal/publicsuffix/publicsuffixes.gz'
	inputs.file(in)
	outputs.file 'build/tmp/publicsuffix/okhttp3/internal/publicsuffix/publicsuffixes'

	dependsOn extractPublicSuffix
	
	commandLine 'gunzip', '-k', in
}

task brotliPublicSuffix(type: Exec) {
	def in = 'build/tmp/publicsuffix/okhttp3/internal/publicsuffix/publicsuffixes'
	inputs.file(in)
	outputs.file 'build/tmp/publicsuffix/okhttp3/internal/publicsuffix/publicsuffixes.br'

	dependsOn popPublicSuffix
	
	if (project.hasProperty('unsup.ci')) {
		environment 'LD_LIBRARY_PATH', './.ci'
		commandLine './.ci/brotli', '-Zk', in
	} else {
		commandLine 'brotli', '-Zk', in
	}
}

task proguardJar(type: Jar) {
	dependsOn proguard
	dependsOn brotliPublicSuffix
	
	from(zipTree('build/tmp/proguard.jar'))
	from('build/tmp/publicsuffix/okhttp3/internal/publicsuffix/publicsuffixes.br') {
		into 'com/unascribed/sup/lib/okhttp3/internal/publicsuffix'
	}
	
	exclude 'com/unascribed/sup/lib/okhttp3/internal/platform/android/**'
	exclude 'com/unascribed/sup/lib/okhttp3/internal/platform/Android*'
	
	exclude 'META-INF/**'
	exclude '**/publicsuffixes.gz'
	exclude '**/*.kotlin_metadata'
	exclude '**/*.kotlin_builtins'
	exclude '**/*.ttc'
	
	reproducibleFileOrder = true
	preserveFileTimestamps = false

	def ver = project.version
	if (ver.endsWith("-SNAPSHOT")) {
		archiveVersion = "${ver}+${snapshotName}"
		ver = "${ver} (${snapshotName})"
	}

	manifest {
		attributes (
			'Main-Class': 'com.unascribed.sup.agent.Agent',
			'Premain-Class': 'com.unascribed.sup.agent.Agent',
			
			'Implementation-Title': 'unsup',
			'Implementation-Version': ver
		)
	}
}

task amendJar {
	dependsOn proguardJar
	def path = proguardJar.archivePath
	doFirst {
		JarAmender.amend(path, Long.parseLong('git show -s --format=%ct HEAD'.execute().text.trim())*1000)
	}
}

build.dependsOn amendJar

task generateBundles {
	def tmp = project.file('build/tmp/bundles')
	def out = project.file('build/bundles')
	doLast {
		Files.move(tmp.toPath(), out.toPath())
	}
}

task cleanBundles(type: Delete) {
	delete 'build/tmp/bundles'
	delete 'build/bundles'
}

ext.platforms.each { plat ->
	def b = task("generateBundle_"+plat, type: Jar) {
		dependsOn cleanBundles
		
		destinationDirectory.set(project.file('build/tmp/bundles'))
		archiveFileName.set(plat+(plat.contains('-') ? '' : '-amd64')+'.jar')
		entryCompression = 'stored'
		
		exclude 'META-INF/**'
		
		configurations.ogldep.resolve().each { f ->
			from zipTree(f)
		}
		configurations.oglnative.resolve().each { f ->
			if (f.name.endsWith("-natives-"+plat+".jar")) {
				from zipTree(f)
			}
		}
		
		reproducibleFileOrder = true
	}
	def c = task("compressBundle_"+plat, type: Exec) {
		dependsOn b
		
		inputs.file b.archivePath
		
		commandLine 'brotli', '-8fj', b.archivePath.absolutePath
	}
	generateBundles.dependsOn c
}

def sigFile = file('build/libs/unsup-'+version+'.jar.sig')

if (project.hasProperty("unsup.signifyKey")) {
	task sign(type: Exec) {
		def pwCmd = project.getProperty("unsup.signifyPasswordCommand");
		doFirst {
			def pipe = new PipedInputStream()
			standardInput pipe
		
			def p = new ProcessBuilder(pwCmd.split(" "))
				.redirectError(ProcessBuilder.Redirect.INHERIT)
				.start()
			p.outputStream.close()
			def pipeout = new PipedOutputStream(pipe)
			p.inputStream.transferTo pipeout
			pipeout.close()
		}		
		dependsOn proguardJar
		inputs.file proguardJar.archivePath
		outputs.file sigFile
		commandLine 'signify', '-S', '-s', project.getProperty("unsup.signifyKey"), '-m', proguardJar.archivePath.absolutePath, '-x', sigFile.absolutePath
	}
} else if (project.hasProperty("unsup.ci")) {
	task sign(type: Exec) {
		doFirst {
			new File('/tmp/signify.sec').text = System.getenv("SIGNIFY_KEY")+'\n'
			standardInput new java.io.ByteArrayInputStream(System.getenv("SIGNIFY_PASSWORD").getBytes("UTF-8"))
		}
		dependsOn proguardJar
		inputs.file proguardJar.archivePath
		outputs.file sigFile
		commandLine './.ci/signify-openbsd', '-S', '-s', '/tmp/signify.sec', '-m', proguardJar.archivePath.absolutePath, '-x', sigFile.absolutePath
	}
}

publishing {
	repositories {
		maven {
			url "https://repo-api.sleeping.town/"
			name 'SleepingTown'
			credentials(PasswordCredentials)
		}
		maven {
			url file('build/maven').toURI().toString()
		}
	}
	publications {
		maven(MavenPublication) {
			groupId = 'com.unascribed'
			artifactId = 'unsup'
			version = project.version

			artifact proguardJar
			if (project.hasProperty("unsup.ci") || project.hasProperty("unsup.signifyKey")) {
				artifact(sigFile) {
					builtBy sign
					extension 'jar.sig'
				}
			}
		}
	}
}

def lwjgl(DependencyHandler deps, String ver, String... modules) {
	deps.ogldep(dependencies.create("org.lwjgl:lwjgl:${ver}"))
	modules.each { module ->
		deps.ogldep(dependencies.create("org.lwjgl:lwjgl-${module}:${ver}"))
	}
	ext.platforms.each { platform ->
		def add = {
			deps.oglnative(dependencies.create(it))
			if (platform == PlatDetect.OS.lwjglName+PlatDetect.ARCH.lwjglSuffix) {
				deps.runtimeOnly(dependencies.create(it))
			}
		}
	
		add("org.lwjgl:lwjgl:${ver}:natives-${platform}")
		modules.each { module ->
			add("org.lwjgl:lwjgl-${module}:${ver}:natives-${platform}")
		}
	}
}
