#!/bin/bash -e
#
# This file is part of unsup.
# Copyright © 2025 Una Kearney
# https://git.sleeping.town/unascribed/unsup
#
# unsup is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# unsup is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with unsup; if not, see <https://www.gnu.org/licenses/>.
#

jq() {
	./.ci/jq "$@"
}

./.ci/brotli -d .ci/jq.br

latest=$(cat ci-version.txt)
latestu=$(echo "$latest" | sed 's/+/%2B/g')
apibase='https://git.sleeping.town/api/v1/repos/unascribed/unsup'
auth="Authorization: token $FORGEJO_KEY"
curl -s -X DELETE -H "$auth" $apibase/releases/tags/SNAPSHOT >/dev/null
curl -s -X DELETE -H "$auth" $apibase/tags/SNAPSHOT >/dev/null

lasttag=$(curl -s "$apibase/releases?draft=false&page=1&limit=1" |jq -r '.[0].tag_name')

resp=$(curl -s -X POST -H 'Content-Type: application/json' -H "$auth" $apibase/releases --data-raw "
{
	\"name\": \"v$latest\",
	\"target_commitish\": \"${CI_COMMIT_SHA-trunk}\",
	\"tag_name\": \"SNAPSHOT\",
	\"draft\": true,
	\"prerelease\": true,
	\"body\": \"Autogenerated snapshot release. See [the commit log](https://git.sleeping.town/unascribed/unsup/compare/$lasttag...trunk) for changes.\\n\\n***This contains the latest changes, fresh off the trunk. It may be unstable and/or completely broken.***\\n\\n**Note**: Snapshots are signed with a different key from releases. See [the 'keys' directory](https://git.sleeping.town/unascribed/unsup/src/branch/trunk/keys) in the repo.\"
}")
echo 'Release create response:'
echo "$resp" |jq .
relid=$(echo "$resp" | jq -r .id)

if [[ -z "$relid" || "$relid" == "null" ]]; then
	exit 1
fi

echo 'Jar attach response:'
curl --fail-with-body -s -X POST -H "$auth" "$apibase/releases/$relid/assets?name=unsup-$latestu.jar" \
	-F "attachment=@build/libs/unsup-$latest.jar" |jq .
echo 'Sig attach response:'
curl --fail-with-body -s -X POST -H "$auth" "$apibase/releases/$relid/assets?name=unsup-$latestu.jar.sig" \
	-F "attachment=@build/libs/unsup-$latest.jar.sig" |jq .
echo 'Component attach response:'
curl --fail-with-body -s -X POST -H "$auth" "$apibase/releases/$relid/assets?name=com.unascribed.unsup.json" \
	-F "attachment=@build/libs/com.unascribed.unsup.json" |jq .

echo 'Undraft response:'
curl --fail-with-body -s -X PATCH -H 'Content-Type: application/json' -H "$auth" "$apibase/releases/$relid" \
	--data-raw '{"draft": false}' |jq .
