/*
 * This file is part of unsup.
 * Copyright © 2025 Una Kearney
 * https://git.sleeping.town/unascribed/unsup
 *
 * unsup is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * unsup is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with unsup; if not, see <https://www.gnu.org/licenses/>.
 */

package com.unascribed.sup.data;

public class SysPropDefs {

	/**
	 * {@value}: Enable or disable debug mode.
	 * <ul>
	 * <li><b>true</b>: Enable verbose log output, disable some "friendly" output options, and enable some
	 * inconvenient debugging behaviors. Debug output is always printed to the unsup.log regardless
	 * of this setting.</li>
	 * <li><b>false</b>: Normal behavior.</li>
	 * </ul>
	 * @since 0.2.0-pre3
	 */
	public static final String DEBUG = "unsup.debug";

	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Print every single request to the log at debug level, even internal
	 * requests.</li>
	 * <li><b>false</b>: Normal behavior.</li>
	 * </ul>
	 * @since 1.1.4
	 */
	public static final String DEBUG_REQUESTS = "unsup.debug.requests";
	
	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Attempt to launch the Puppet even in standalone mode.</li>
	 * <li><b>false</b>: Only launch the Puppet in agent mode.</li>
	 * </ul>
	 * @since 0.0.4
	 */
	public static final String GUI_IN_STANDALONE = "unsup.guiInStandalone";
	/**
	 * {@value}
	 * @deprecated (Since 1.1-beta1) Setting to {@code true} is equivalent to setting {@link #BEHAVIOR} to auto.
	 * @since 0.3.0-pre1
	 */
	@Deprecated
	public static final String DISABLE_RECONCILIATION = "unsup.disableReconciliation";
	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Pretend use_envs is set to false. This will cause unsup to download all
	 * files regardless of their configured environment.</li>
	 * <li><b>false</b>: Honor use_envs.</li>
	 * </ul>
	 * @since 1.1-pre3
	 */
	public static final String IGNORE_ENVS = "unsup.ignoreEnvs";
	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Exit the Agent if the Puppet crashes. Only useful when debugging the Puppet.</li>
	 * <li><b>false</b>: Continue without a GUI if the Puppet crashes.</li>
	 * </ul>
	 * @since 1.1-pre5
	 */
	public static final String ABORT_ON_PUPPET_CRASH = "unsup.abortOnPuppetCrash";
	/**
	 * {@value}: The number of downloads to perform in parallel. Defaults to 6, a reasonable tradeoff on most
	 * computers and most internet connections. People with slow connections or computers may want
	 * to reduce this to 1.
	 * @since 1.1-beta1
	 */
	public static final String DOWNLOAD_WORKERS = "unsup.downloadWorkers";
	
	/**
	 * {@value}: Set how much control unsup should give to the user as to how updates should proceed.
	 * <ul>
	 * <li><b>auto</b>: No control. All file conflicts are auto-accepted and updates are auto-applied.</li>
	 * <li><b>semi</b>: Updates are auto-applied, but file conflicts still prompt the user.</li>
	 * <li><b>manual</b>: Default. Updates and file conflicts prompt the user.</li>
	 * </ul>
	 * @since 1.1-beta1
	 */
	public static final String BEHAVIOR = "unsup.behavior";

	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Do everything when updating except actually saving files to disk. Can be
	 * used to verify the consistency of a manifest.</li>
	 * <li><b>false</b>: Normal behavior.</li>
	 * </ul>
	 * @since 1.1-beta1
	 */
	public static final String DRY_RUN = "unsup.dryRun";
	
	/**
	 * {@value}: Override the language rather than using the one detected by Java.
	 * <p>
	 * Value should be an IETF BCP 47 language tag, or one of the special values:
	 * <ul>
	 * <li><b>tok</b>: Toki Pona</li>
	 * <li><b>en-XA</b>: Autogenerated "accented English"</li>
	 * <li><b>en-PIG</b>: Autogenerated Pig Latin</li>
	 * </ul>
	 * @since 1.1-pre1
	 */
	public static final String LANGUAGE = "unsup.language";

	/**
	 * {@value}: The URL to an unsup.ini to use if none is available in the working directory.
	 * @since 1.1.3
	 */
	public static final String BOOTSTRAP_URL = "unsup.bootstrapUrl";

	/**
	 * {@value}: The public key to use to verify {@code ${unsup.bootstrapUrl}.sig}, in the same
	 * format as {@code public_key} in the config.
	 * @since 1.1.3
	 */
	public static final String BOOTSTRAP_KEY = "unsup.bootstrapKey";
	
	
	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Force open the flavor selection dialog. Packwiz mode only. Prefer setting
	 * offer_change_flavors in unsup.ini for packs where the user may want to change flavors often.</li>
	 * <li><b>false</b>: Normal behavior.</li>
	 * </ul>
	 * @since 0.2.0-pre3
	 */
	public static final String PACKWIZ_CHANGE_FLAVORS = "unsup.packwiz.changeFlavors";
	

	/**
	 * {@value}: Wrap execution of the Puppet in this command. Only for debugging the Puppet.
	 * @since 1.1-pre5
	 */
	public static final String PUPPET_WRAPPER_COMMAND = "unsup.puppet.wrapperCommand";
	/**
	 * {@value}: <ul>
	 * <li><b>true</b>: Pass all -Dorg.lwjgl.* system properties through to the Puppet. Useful on
	 * some weird Linux distros. <b><i>Do not use to apply the glfw-wayland-minecraft hack fork!</i></b></li>
	 * <li><b>false</b>: Only pass certain system properties through to the Puppet.</li>
	 * </ul>
	 * @since 1.1-pre8
	 */
	public static final String PUPPET_PASS_ALL_LWJGL_ARGS = "unsup.puppet.passAllLwjglArgs";
	
	/**
	 * {@value}: Set which mode the Puppet will use.
	 * <ul>
	 * <li><b>auto</b>: Let unsup decide which implementation is best.</li>
	 * <li><b>swing</b>: Force usage of the legacy Swing puppet.</li>
	 * <li><b>opengl</b>: Force usage of the modern OpenGL puppet.</li>
	 * </ul>
	 * @since 1.1-pre1
	 */
	public static final String PUPPET_MODE = "unsup.puppetMode";
	
	/**
	 * {@value}: Set which platform the OpenGL Puppet will use.
	 * <ul>
	 * <li><b>auto</b>: Let GLFW decide which implementation is best.</li>
	 * <li><b>win32</b>: Force usage of the Windows platform.</li>
	 * <li><b>cocoa</b>: Force usage of the macOS Cocoa platform.</li>
	 * <li><b>wayland</b>: Force usage of the Wayland platform.</li>
	 * <li><b>x11</b>: Force usage of the X11 platform.</li>
	 * <li><b>null</b>: Force usage of the dummy platform. Almost never useful.</li>
	 * </ul>
	 * @since 1.1-pre1
	 */
	public static final String PUPPET_PLATFORM = "unsup.puppet.opengl.platform";
	
}
