#
# This file is part of unsup.
# Copyright © 2020-2021, 2023-2025 Una Kearney
# https://git.sleeping.town/unascribed/unsup
#
# unsup is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# unsup is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with unsup; if not, see <https://www.gnu.org/licenses/>.
#

use_envs=true
recognize_nogui=true
update_mmc_pack=true

[env.client]
marker=net.minecraft.client.main.Main

[env.server]
marker=*

[mmc-component-map]
minecraft=net.minecraft
minecraft=net.fabricmc.intermediary
minecraft=org.quiltmc.hashed
unsup=com.unascribed.sup
unsup=com.unascribed.unsup
fabric=net.fabricmc.fabric-loader
quilt=org.quiltmc.quilt-loader
liteloader=com.mumfrey.liteloader
forge=net.minecraftforge
neoforge=net.neoforged
nilloader=com.unascribed.nilloader
